### 3.5.1. Install pg-rex-operation-tools
# Copy all RPM packages to /var/tmp directory at once
- name: Copy all PG-REX operation tools RPM packages to nodes
  copy:
    src: "{{ item }}"
    dest: /var/tmp/
  with_items:
    - "{{ PG_REX_OPERATION_TOOLS_SCRIPT_RPM }}"
    - "{{ NET_OPENSSH_RPM }}"
    - "{{ PERL_IO_TTY_RPM_URL.split('/')[-1] }}"
  register: rpm_copy

# Install all RPM packages together using dnf command
- name: Install all PG-REX operation tools RPM packages
  dnf:
    name:
      - "/var/tmp/{{ PG_REX_OPERATION_TOOLS_SCRIPT_RPM }}"
      - "/var/tmp/{{ NET_OPENSSH_RPM }}"
      - "/var/tmp/{{ PERL_IO_TTY_RPM_URL.split('/')[-1] }}"
    disable_gpg_check: True
    state: present

### Install lsof perl-File-Compare
### The PG-REX user manual does not mention it,
### but the pg rex operation tools require lsof and perl-File-Compare packages
- name: Install lsof and perl-File-Compare
  dnf:
    name: ['lsof', 'perl-File-Compare']
    #enablerepo: highavailability
    state: present

# Verify installation of all packages
- name: Verify installed packages
  shell: "rpm -qa | grep -E 'perl-IO-Tty|Net_OpenSSH|pg-rex|lsof|perl-File-Compare'"
  register: installed_packages
  changed_when: false

# Display the list of installed packages
- name: Display installed packages
  debug:
    msg: "{{ installed_packages.stdout_lines }}"
