- import_playbook: ./ansible-resource-settings/01-environment-excel-download.yml
- import_playbook: ./ansible-resource-settings/10-edit-environment-excel.yml
- import_playbook: ./ansible-resource-settings/11-transfer-environment-csv.yml
