# Copy pm_extra_tools to nodes
- name: Copy pm_extra_tools to nodes
  copy:
    src: "{{ pm_extra_tools_url }}"
    dest: /var/tmp/
  register: rc_copy

# Install pm_extra_tools
- name: Install pm_extra_tools
  yum:
    name: "{{ rc_copy.dest }}"
    disable_gpg_check: True
    state: present
