all:
  vars:
    ### ansible-os-common-settings
    S_LAN_INTERFACE: eth1
    D_LAN_INTERFACE: eth2
    IC_LAN_INTERFACES:
      - eth3
      - eth4
    M_LAN_INTERFACE: eth5
    SYSTEM_LOCALE: ja_JP.UTF-8
    SYSTEM_TIMEZONE: Asia/Tokyo

    ### ansible-virtualbmc
    VBMC_HYPERVISOR: vbox
    VBMC_VERSION: devel-vbox-2.0
    VBMC_VENV_DIR: ./venv-vbmc
    VBMC_IPMI_IF: eth0
    ### STONITH LAN
    VBMC_WSL2_SUBNET_IP: 192.168.199.1

    ### ansible-pacemaker
    HACLUSTER_PASSWORD: pacemaker
    CLUSTER_NAME: pgrex_cluster
    FENCE_AGENTS: [fence_ipmilan]
    PM_EXTRA_TOOLS_URL: "https://github.com/linux-ha-japan/pm_extra_tools/releases/download/pm_extra_tools-1.6/pm_extra_tools-1.6-1.el9.noarch.rpm"

    ### ansible-postgresql
    PG_REV: '17.4-1PGDG'

    ### ansible-pg-rex-operation-tools
    ### for perl-IO-Tty-1.16-4.el9.x86_64.rpm
    PERL_IO_TTY_RPM_URL: "https://dl.rockylinux.org/pub/rocky/9/devel/x86_64/os/Packages/p/perl-IO-Tty-1.16-4.el9.x86_64.rpm"
    ### for Net_OpenSSH-0.62-1.el9.x86_64.rpm and pg-rex_operation_tools_script-17.0-1.el9.noarch.rpm
    PG_REX_TOOLS_URL: "https://github.com/ossc-db/PG-REX-tools/releases/download/PG-REX_17_1/pg-rex17-1.0-1.tar.gz"
    NET_OPENSSH_RPM: Net_OpenSSH-0.62-1.el9.x86_64.rpm
    PG_REX_OPERATION_TOOLS_SCRIPT_RPM: pg-rex_operation_tools_script-17.0-1.el9.noarch.rpm
    ### Replication listener virtual IP address
    PG_REPLICATION_ADDRESS: 192.168.77.201
    PG_REPLICATION_USER: repuser
    PG_REPLICATION_PASSWORD: reppasswd

    ### ansible-resource-settings
    ### Environment excel
    ENVIRONMENT_EXCEL: "environment-excel.xlsx"
    ### Environment excel sheet
    ENVIRONMENT_EXCEL_SHEET: "RHEL9.4"
    ### Environment csv
    ENVIRONMENT_CSV: "pm_pcsgen_env.csv"
    ### Virtual IP address for connecting to the primary side of PostgreSQL
    PG_PRIMARY_VIRTUAL_IP_ADDRESS: 192.168.76.201 
    ### Virtual IP address for connecting to the standby side of PostgreSQL
    PG_STANDBY_VIRTUAL_IP_ADDRESS: 192.168.76.202
    ### Netmask for S-LAN
    S_LAN_NETMASK: 24
    ### Netmask for D-LAN
    D_LAN_NETMASK: 24
    ### IP address of the network to be monitored (for ping resource)
    S_LAN_DEFAULT_GATEWAY_IP_ADDRESS: 192.168.76.1
    ### Device name to be monitored(for storage-mon resource)
    MONITORED_DEVICE_NAME: "/dev/sda"

  hosts:
    pgrex01:
      S_LAN_ADDR: 192.168.76.101
      D_LAN_ADDR: 192.168.77.101
      IC_LAN1_ADDR: 192.168.78.101
      IC_LAN2_ADDR: 192.168.79.101
      M_LAN_ADDR: 192.168.80.101
      ansible_host: 192.168.80.101
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./vagrant/.vagrant/machines/pgrex01/virtualbox/private_key
    pgrex02:
      S_LAN_ADDR: 192.168.76.102
      D_LAN_ADDR: 192.168.77.102
      IC_LAN1_ADDR: 192.168.78.102
      IC_LAN2_ADDR: 192.168.79.102
      M_LAN_ADDR: 192.168.80.102
      ansible_host: 192.168.80.102
      ansible_user: vagrant
      ansible_ssh_private_key_file: ./vagrant/.vagrant/machines/pgrex02/virtualbox/private_key

### ansible-virtualbmc
hacluster_vbmc:
  hosts:
    pgrex01:
      IPMI_IP: 192.168.199.91
      IPMI_USER: pacemaker
      IPMI_PASS: pacemakerpass1
    pgrex02:
      IPMI_IP: 192.168.199.92
      IPMI_USER: pacemaker
      IPMI_PASS: pacemakerpass1

### ansible-pacemaker
hacluster:
  hosts:
    pgrex01:
    pgrex02:

### ansible-pgrex
hacluster_pgrex:
  children:
    hacluster:
  vars:
    PG_PASSWORD: postgres
    PG_DATA: /dbfp/pgdata/data
    PG_WAL: /dbfp/pgwal/pg_wal
    PG_ARCHIVE: /dbfp/pgarch/arc1
    PG_PORT: 5432
