# Raw module used for bootstrap: install Python 3 if missing (required by Ansible)
- name: Ensure Python 3 is installed
  raw: which python3 || (yum -qy install python3 && exit 100)
  register: _yum
  changed_when: _yum.rc != 0
  failed_when: _yum.rc not in [0, 100]

# Required after ensuring Python is available
- name: Gather system facts
  setup:

# Retrieves the list of installed locales on the system
- name: Check installed locales
  command: localectl list-locales
  register: _localectl_list_locales
  changed_when: false

# Installs glibc-langpack-<lang> if not already present (e.g., glibc-langpack-ja)
- name: Install required locale package
  yum:
    name: "glibc-langpack-{{ SYSTEM_LOCALE.split('_')[0] }}"
  when: SYSTEM_LOCALE not in _localectl_list_locales.stdout_lines

# Reads current locale settings for comparison
- name: Get current locale configuration
  command: localectl
  register: _localectl
  changed_when: false

# Sets system locale only if it differs from the desired value
- name: Set system locale if not already set
  command: "localectl set-locale LANG={{ SYSTEM_LOCALE }}"
  when: "'System Locale: LANG=' + SYSTEM_LOCALE not in _localectl.stdout"

# Reads current timezone settings for comparison
- name: Get current timezone configuration
  command: timedatectl
  register: _timedatectl
  changed_when: false

# Sets timezone only if it differs from the desired setting
- name: Set system timezone if not already set
  command: "timedatectl set-timezone {{ SYSTEM_TIMEZONE }}"
  when: "'Time zone: ' + SYSTEM_TIMEZONE not in _timedatectl.stdout"

# Writes all inventory hosts' IPs and names into /etc/hosts using M_LAN_ADDR from inventory
- name: Add host entries to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {% for item in groups.all %}
      {{ hostvars[item].M_LAN_ADDR }} {{ item }} {{ item }}
      {% endfor %}
