- hosts: localhost
  gather_facts: no

  tasks:
    - name: Download pm_extra_tools
      get_url:
        url="{{ pm_extra_tools_url }}"
        dest=./roles/pm_extra_tools-install/files/
        timeout=60
      tags: download

- hosts: hacluster
  become: true
  gather_facts: no
  max_fail_percentage: 0

  roles:
    - role: pm_extra_tools-install
