- hosts: localhost
  gather_facts: no

  tasks:
    - name: Download pm_extra_tools
      get_url:
        url="https://github.com/linux-ha-japan/pm_extra_tools/releases/download/pm_extra_tools-{{item.rev}}/{{item.package}}"
        dest=./roles/pm_extra_tools-install/files/
        timeout=60
      with_items:
        - {rev: 1.6, package: pm_extra_tools-1.6-1.el9.noarch.rpm }
      tags: download

- hosts: hacluster
  become: true
  gather_facts: no
  max_fail_percentage: 0

  roles:
    - role: pm_extra_tools-install
